#!/bin/bash
apt-get update -qq

apt-get install --force-yes -y -qq wget python git nginx uwsgi uwsgi-plugin-python python-virtualenv python-uwsgidecorators python-dev libffi-dev libmysqlclient-dev python-jinja2

# add environment variables
$(./config.py)

# git clone
pushd . 
cd /usr/share/nginx/html/
git init
git remote add origin $UPSCALE_REPOSITORY_URL 
git fetch origin
git checkout -b master
git reset origin/master --hard
popd

# run prebuild.d scripts
pushd .
cd /usr/share/nginx/html/
if [ -d .upscale/pre-build.d/ ] ; then
for script in `ls .upscale/pre-build.d/* | sort -V`; do 
echo Executing $script
chmod +x ./$script
./$script
done
fi
popd

pushd .
for script in `ls build.d/* | sort -V`; do 
echo Executing $script
chmod +x ./$script
./$script
done
popd

# run postbuild.d scripts
pushd .
cd /usr/share/nginx/html/
if [ -d .upscale/post-build.d/ ] ; then
for script in `ls .upscale/post-build.d/* | sort -V`; do 
echo Executing $script
chmod +x ./$script
./$script
done
fi
popd

