#!/bin/bash

cd /usr/share/nginx/html/

# change user to prevent issues with permissions
su www-data
git init
git remote add origin $UPSCALE_REPOSITORY_URL 
git fetch origin
git checkout -b master
git reset origin/master --hard

